### PR TITLE
Enqueue the livereload script correctly

### PR DESCRIPTION
**Pull request by jaredrcleghorn**

### CODE REVIEW

**Comment by carylwyatt** [comment]
@jaredrcleghorn It looks like you just moved the function up in the file? Did that do the trick?

**Comment by jaredrcleghorn** [comment]
@carylwyatt I think it's kind of hard to tell from the diff, but I moved that `if` block into the `roots_ualib_scripts` function, which is the callback for the `wp_enqueue_scripts` hook, so that the livereload script gets enqueued at the proper time.

**Comment by jaredrcleghorn** [comment]
@carylwyatt That's what the debug notice was about—a script being enqueued outside of that hook.

**Comment by jaredrcleghorn** [comment]
@carylwyatt Livereload still didn't seem to work when I tried it, but that may just be a problem with the script that we're using. It did get rid of the debug notices though.

**Comment by carylwyatt** [comment]
Oh, right! I'll go ahead and merge this in to dev. I'm making an update to the theme sometime soon (there's a weird CSS bug in the header that needs attention), so I'll pull this in to the deploy version with that later this week. 

Thanks for fixing! 🙌

**Pull request merged**
